"""del_user

Revision ID: 622fedbf3d48
Revises: c2a37daa7278
Create Date: 2023-06-13 11:09:47.730090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "622fedbf3d48"
down_revision = "c2a37daa7278"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
