"""first_migration

Revision ID: c2a37daa7278
Revises: d40f40264827
Create Date: 2023-06-10 02:30:05.705167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2a37daa7278"
down_revision = "d40f40264827"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
